
import type { Metadata } from "next";
import Navigation from "./navigation";
import Titlebar from "./titlebar";
import "./globals.css";
import Controls from "./controls";
import Script from "next/script";
export const metadata: Metadata = 
{
	title: "Codi",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) 
{
	/*
		Agar development UI lebih cepat, maka menggunakan template dari assets.agapedimas.com
		dan plugin tersebut membutuhkan JQuery
	*/
	return (
		<html lang="en" suppressHydrationWarning={true}>
			<head>
				<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
				<script src="https://assets.agapedimas.com/ui/v3/head.js"></script>
				<script src="https://assets.agapedimas.com/ui/v3/components.js"></script>
				<script src="https://assets.agapedimas.com/ui/v3/style.js"></script>
				<script src="https://assets.agapedimas.com/ui/v3/events.js"></script>
			</head>
			<body>
				<script src="https://assets.agapedimas.com/ui/v3/main.js"></script>
				<Titlebar/>
				<div className="root">
					<Controls/>
					<Navigation/>
					<div className="main">
						{children}
					</div>
					<Script src="/scripts.js"></Script>
				</div>
			</body>
		</html>
	);
}
