
import type { Metadata } from "next";
import "./styles.css";

export const metadata: Metadata = 
{
	title: 
	{ 
		default: "Codi",
		template: "%s | Codi"
	},
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) 
{
	/*
		Agar development UI lebih cepat, maka menggunakan template dari assets.agapedimas.com
		dan plugin tersebut membutuhkan JQuery
	*/
	return (
		<html lang="id" suppressHydrationWarning={true}>
			<head>
				<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"/>
				<script src="https://assets.agapedimas.com/ui/v3/head.js"/>
				<script src="https://assets.agapedimas.com/ui/v3/components.js"/>
				<script src="https://assets.agapedimas.com/ui/v3/style.js"/>
				<script src="https://assets.agapedimas.com/ui/v3/events.js"/>
			</head>
			<body>
				<script src="https://assets.agapedimas.com/ui/v3/main.js"/>
				{children}
			</body>
		</html>
	);
}
